# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: docs/conf.py
# might want to do this in future:
  # fail_on_warning: true

# Do not build the docs in additional formats (e.g. PDF and ePub), use default
formats: []

# Optionally install options and requirements required to build your docs
python:
  install:
    - method: pip
      path: .
      extra_requirements:
         - doc
    - requirements: docs/requirements.txt
