jobs:
- job: hera_cal
  pool:
    vmImage: "ubuntu-latest"
  variables:
    PYTHON: "3.9"
    ENV_NAME: hera_cal_tests
    WITH_SUDO: true

  steps:
  - bash: |
      cd ../
      git clone https://github.com/HERA-Team/hera_cal.git
      cd s
    displayName: clone hera_cal

  - bash: wget -qO- https://micro.mamba.pm/api/micromamba/linux-64/latest | sudo tar -C / -xvj bin/micromamba
    displayName: Install Micromamba

  - bash: |
      micromamba info
      # need these to add gxx and gcc to build novas and cython
      micromamba create --name=${ENV_NAME}  python=$PYTHON gxx gcc -f ../hera_cal/ci/${ENV_NAME}.yml -yq
    displayName: configure conda environment

  - bash: |
      source ./ci/_activate_current_env.sh
      micromamba list -n ${ENV_NAME}
      # check that the python version matches the desired one; exit immediately if not
      PYVER=`python -c "import sys; print('{:d}.{:d}'.format(sys.version_info.major, sys.version_info.minor))"`
      if [[ $PYVER != $PYTHON ]]; then
        exit 1;
      fi
    displayName: Verify Mamba Config

  - bash: |
      source ./ci/_activate_current_env.sh
      pip install --no-deps .
      cd ../hera_cal
      pip install --no-deps .
      mkdir test-reports
      python -m pytest hera_cal --junitxml=test-reports/xunit.xml
    displayName: run hera_cal tests

- job: hera_qm
  pool:
    vmImage: "ubuntu-latest"
  variables:
    PYTHON: "3.9"
    ENV_NAME: hera_qm_tests
    WITH_SUDO: true

  steps:
  - bash: |
      cd ../
      git clone https://github.com/HERA-Team/hera_qm.git
      cd s
    displayName: clone hera_qm

  - bash: wget -qO- https://micro.mamba.pm/api/micromamba/linux-64/latest | sudo tar -C / -xvj bin/micromamba
    displayName: Install Micromamba

  - bash: |
      micromamba info
      # need these to add gxx and gcc to build novas and cython
      micromamba create --name=${ENV_NAME}  python=$PYTHON gxx gcc -f ../hera_qm/ci/${ENV_NAME}.yml -yq
    displayName: configure conda environment

  - bash: |
      source ./ci/_activate_current_env.sh
      micromamba list -n ${ENV_NAME}
      # check that the python version matches the desired one; exit immediately if not
      PYVER=`python -c "import sys; print('{:d}.{:d}'.format(sys.version_info.major, sys.version_info.minor))"`
      if [[ $PYVER != $PYTHON ]]; then
        exit 1;
      fi
    displayName: Verify Mamba Config

  - bash: |
      source ./ci/_activate_current_env.sh
      pip install --no-deps .
      cd ../hera_qm
      pip install --no-deps .
      mkdir test-reports
      python -m pytest hera_qm --junitxml=test-reports/xunit.xml
    displayName: run hera_qm tests

- job: pyradiosky
  pool:
    vmImage: "ubuntu-latest"
  variables:
    PYTHON: "3.9"
    ENV_NAME: tests
    WITH_SUDO: true

  steps:
  - bash: |
      cd ../
      git clone https://github.com/RadioAstronomySoftwareGroup/pyradiosky
      cd s
    displayName: clone pyradiosky

  - bash: wget -qO- https://micro.mamba.pm/api/micromamba/linux-64/latest | sudo tar -C / -xvj bin/micromamba
    displayName: Install Micromamba

  - bash: |
      micromamba info
      # need these to add gxx and gcc to build novas and cython
      # note different spelling of yaml extension
      micromamba create --name=${ENV_NAME}  python=$PYTHON gxx gcc -f ../pyradiosky/ci/${ENV_NAME}.yaml -yq
    displayName: configure conda environment

  - bash: |
      source ./ci/_activate_current_env.sh
      micromamba list -n ${ENV_NAME}
      # check that the python version matches the desired one; exit immediately if not
      PYVER=`python -c "import sys; print('{:d}.{:d}'.format(sys.version_info.major, sys.version_info.minor))"`
      if [[ $PYVER != $PYTHON ]]; then
        exit 1;
      fi
    displayName: Verify Mamba Config

  - bash: |
      source ./ci/_activate_current_env.sh
      pip install --no-deps .
      cd ../pyradiosky
      pip install --no-deps .
      mkdir test-reports
      python -m pytest pyradiosky --junitxml=test-reports/xunit.xml
    displayName: run pyradiosky tests

- job: pyuvsim
  pool:
    vmImage: "ubuntu-latest"
  variables:
    PYTHON: "3.9"
    ENV_NAME: tests
    WITH_SUDO: true

  steps:
  - bash: |
      cd ../
      git clone https://github.com/RadioAstronomySoftwareGroup/pyuvsim
      cd s
    displayName: clone pyuvsim

  - bash: wget -qO- https://micro.mamba.pm/api/micromamba/linux-64/latest | sudo tar -C / -xvj bin/micromamba
    displayName: Install Micromamba

  - bash: |
      micromamba info
      # need these to add gxx and gcc to build novas and cython
      # note different spelling of yaml extension
      micromamba create --name=${ENV_NAME}  python=$PYTHON gxx gcc -f ../pyuvsim/ci/${ENV_NAME}.yaml -yq
    displayName: configure conda environment

  - bash: |
      source ./ci/_activate_current_env.sh
      micromamba list -n ${ENV_NAME}
      # check that the python version matches the desired one; exit immediately if not
      PYVER=`python -c "import sys; print('{:d}.{:d}'.format(sys.version_info.major, sys.version_info.minor))"`
      if [[ $PYVER != $PYTHON ]]; then
        exit 1;
      fi
    displayName: Verify Mamba Config

  - bash: |
      source ./ci/_activate_current_env.sh
      pip install --no-deps .
      cd ../pyuvsim
      pip install --no-deps .
      mkdir test-reports
      python -m pytest pyuvsim --junitxml=test-reports/xunit.xml
    displayName: run pyuvsim tests
