jobs:
- job: hera_cal
  pool:
    vmImage: "ubuntu-latest"
  variables:
    PYTHON: "3.9"
    ENV_NAME: hera_cal
    WITH_SUDO: true

  steps:
  - bash: wget -qO- https://micro.mamba.pm/api/micromamba/linux-64/latest | sudo tar -C / -xvj bin/micromamba
    displayName: Install Micromamba

  - bash: |
      micromamba info
      # need these to add gxx and gcc to build novas and cython
      micromamba create --name=${ENV_NAME}  python=$PYTHON gxx gcc -f ci/${ENV_NAME}.yml -yq
    displayName: configure conda environment

  - bash: |
      source ./ci/_activate_current_env.sh
      micromamba list -n ${ENV_NAME}
      # check that the python version matches the desired one; exit immediately if not
      PYVER=`python -c "import sys; print('{:d}.{:d}'.format(sys.version_info.major, sys.version_info.minor))"`
      if [[ $PYVER != $PYTHON ]]; then
        exit 1;
      fi
    displayName: Verify Mamba Config

  - bash: |
      source activate ${ENV_NAME}
      pip install --no-deps .
      cd ../
      git clone https://github.com/HERA-Team/hera_cal.git
      cd hera_cal
      pip install --no-deps .
      mkdir test-reports
      python -m pytest hera_cal -n auto --junitxml=test-reports/xunit.xml
    displayName: run hera_cal tests

- job: hera_qm
  pool:
    vmImage: "ubuntu-latest"
  variables:
    PYTHON: "3.9"
    ENV_NAME: hera_qm
    WITH_SUDO: true

  steps:
  - bash: wget -qO- https://micro.mamba.pm/api/micromamba/linux-64/latest | sudo tar -C / -xvj bin/micromamba
    displayName: Install Micromamba

  - bash: |
      micromamba info
      # need these to add gxx and gcc to build novas and cython
      micromamba create --name=${ENV_NAME}  python=$PYTHON gxx gcc -f ci/${ENV_NAME}.yml -yq
    displayName: configure conda environment

  - bash: |
      source ./ci/_activate_current_env.sh
      micromamba list -n ${ENV_NAME}
      # check that the python version matches the desired one; exit immediately if not
      PYVER=`python -c "import sys; print('{:d}.{:d}'.format(sys.version_info.major, sys.version_info.minor))"`
      if [[ $PYVER != $PYTHON ]]; then
        exit 1;
      fi
    displayName: Verify Mamba Config

  - bash: |
      source activate ${ENV_NAME}
      pip install --no-deps .
      cd ../
      git clone https://github.com/HERA-Team/hera_qm.git
      cd hera_qm
      pip install --no-deps .
      mkdir test-reports
      python -m pytest hera_qm -n auto --junitxml=test-reports/xunit.xml
    displayName: run hera_qm tests
