jobs:
- job: ext_pip
  pool:
    vmImage: "ubuntu-latest"
  variables:
    WITH_SUDO: true
  strategy:
    matrix:
      hera_cal:
          NAME: "hera_cal"
          PYTHON: "3.13"
          REPO: https://github.com/HERA-Team/hera_cal.git
          PIP_INSTALL_ARGS: ".[dev]"
          PYTEST_ARGS: "-n auto"
      hera_qm:
          NAME: "hera_qm"
          PYTHON: "3.12"
          REPO: https://github.com/HERA-Team/hera_qm.git
          PIP_INSTALL_ARGS: ".[tests]"
          PYTEST_ARGS: "-n auto"
      pyradiosky:
          NAME: "pyradiosky"
          PYTHON: "3.13"
          REPO: https://github.com/RadioAstronomySoftwareGroup/pyradiosky.git
          PIP_INSTALL_ARGS: ".[dev]"
          PYTEST_ARGS: ""
      SSINS:
          NAME: "SSINS"
          PYTHON: "3.13"
          REPO: https://github.com/mwilensky768/SSINS.git
          PIP_INSTALL_ARGS: ".[plot]"
          PYTEST_ARGS: "-n auto"

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(PYTHON)

  - bash: |
      cd ../
      git clone ${REPO}
      cd s
    displayName: clone $(NAME)

  - bash: |
      pip install .[test]
    displayName: install pyuvdata

  - bash: |
      cd ../${NAME}
      pip install ${PIP_INSTALL_ARGS}
    displayName: install $(NAME)

  # re-install pyuvdata last to ensure the checked out code is installed
  # (because sometimes hera_cal pins to weird things and overwrites the earlier install.)
  # keep the earlier install because it ensures the right dependencies are grabbed.
  - bash: |
      cd s
      pip install .[test]
    displayName: install pyuvdata

  - bash: |
      pip list
    displayName: Environment Info

  - bash: |
      cd ../${NAME}
      pytest ${PYTEST_ARGS}
    displayName: run $(NAME) tests


- job: ext_conda
  pool:
    vmImage: "ubuntu-latest"
  strategy:
    matrix:
      pyuvsim:
        NAME: "pyuvsim"
        PYTHON: "3.12"
        ENV_NAME: pyuvsim_tests_openmpi
        WITH_SUDO: true
        REPO: https://github.com/RadioAstronomySoftwareGroup/pyuvsim.git
        PYTEST_ARGS: "-n auto"

  steps:
  - bash: |
      cd ../
      git clone ${REPO}
      cd s
    displayName: clone $(NAME)

  - bash: |
        wget -O Miniforge3.sh "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
        bash Miniforge3.sh -b -p "${HOME}/conda"
    displayName: Install Conda from Miniforge

  - bash: |
      # point to this conda install, not the default conda on Azure pipelines hosts
      # need these to add gxx and gcc to build novas and cython
      source "${HOME}/conda/etc/profile.d/conda.sh"
      conda create --name=${ENV_NAME} python=$PYTHON gxx gcc -yq
      conda env update --name=${ENV_NAME} -f ../$(NAME)/ci/${ENV_NAME}.yaml
    displayName: configure conda environment

  - bash: |
      source "${HOME}/conda/etc/profile.d/conda.sh"
      conda activate ${ENV_NAME}
      conda info
      conda list
      # check that the python version matches the desired one; exit immediately if not
      PYVER=`python -c "import sys; print('{:d}.{:d}'.format(sys.version_info.major, sys.version_info.minor))"`
      if [[ $PYVER != $PYTHON ]]; then
        exit 1;
      fi
    displayName: Verify Conda Config

  # install this version of pyuvdata
  - bash: |
      source "${HOME}/conda/etc/profile.d/conda.sh"
      conda activate ${ENV_NAME}
      pip install --no-deps .
    displayName: install pyuvdata

  - bash: |
      source "${HOME}/conda/etc/profile.d/conda.sh"
      conda activate ${ENV_NAME}
      cd ../$(NAME)
      pip install --no-deps .
    displayName: install $(NAME)

  - bash: |
      source "${HOME}/conda/etc/profile.d/conda.sh"
      conda activate ${ENV_NAME}
      cd ../$(NAME)
      pytest ${PYTEST_ARGS}
    displayName: run $(NAME) tests
