name: Warning Tests

on:
  push:
    # This should disable running the workflow on tags, according to the
    # on.<push|pull_request>.<branches|tags> GitHub Actions docs.
    branches:
      - "*"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  warning_test:
    name: Warning Test
    env:
      PYTEST_OPTIONS: ${{ case(matrix.coverage == true, '--cov=pyuvdata --cov-config=.coveragerc --cov-report xml:coverage.xml', '') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: 3.13
            pip-options: "dev"
            coverage: true
          # currently (April 2026), python-casacore does not build properly from pypi on python 3.14
          # also, cython's coverage plugin causes errors when building from pypi on python 3.14
          - python-version: 3.14
            pip-options: "test"
            coverage: false
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install
        run: |
          CFLAGS="-DCYTHON_TRACE=1 -DCYTHON_TRACE_NOGIL=1" pip install -e .[${{ matrix.pip-options }}]
          pip install pytest-xdist

      - name: Environment Info
        run: |
          pip list

      - name: Run Tests
        run: |
          pytest -W error -n auto ${PYTEST_OPTIONS}

      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        if: matrix.coverage == true && success()
        with:
          token: ${{secrets.CODECOV_TOKEN}} #required
          files: ./coverage.xml #optional
          fail_ci_if_error: true
